[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Backend externo no Render
[[redirects]]
  from = "/api/destination"
  to = "https://proximaviagemapi.onrender.com/api/destination"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/destination/fallback"
  to = "https://proximaviagemapi.onrender.com/api/destination/fallback"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Fallback para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Configurações de cache para resolver problemas de cache
[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

# Cache específico para assets estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache para arquivos de configuração
[[headers]]
  for = "/ads.txt"
  [headers.values]
    Content-Type = "text/plain"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    Cache-Control = "public, max-age=86400"

# Cache para arquivos de verificação
[[headers]]
  for = "/google*.html"
  [headers.values]
    Content-Type = "text/html"
    Cache-Control = "public, max-age=86400"
