[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Proxy para API do backend - tentar endpoint principal primeiro
[[redirects]]
  from = "/api/destination"
  to = "https://proximaviagem.fly.dev/api/destination"
  status = 200
  force = true

[[redirects]]
  from = "/api/destination/fallback"
  to = "https://proximaviagem.fly.dev/api/destination/fallback"
  status = 200
  force = true

[[redirects]]
  from = "/api/health"
  to = "https://proximaviagem.fly.dev/api/health"
  status = 200
  force = true

# Fallback para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/ads.txt"
  [headers.values]
    Content-Type = "text/plain"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
