[build]
  base = "frontend"
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Backend externo no Render
[[redirects]]
  from = "/api/destination"
  to = "https://proximaviagemapi.onrender.com/api/destination"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/api/destination/fallback"
  to = "https://proximaviagemapi.onrender.com/api/destination/fallback"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# Fallback para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/ads.txt"
  [headers.values]
    Content-Type = "text/plain"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Content-Type = "text/plain"

[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
